title: Alexandra Borschke # your name (or website title) here
logo: "/images/circle_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a strong background in academic research and project management.
  <br>
  I am currently looking for collaboration and job opportunities involving challenging and exciting projects. If you’re looking for someone to improve your company’s performance through data-driven solutions, feel free to contact me via LinkedIn!
  <br><br>
  Tools: Python, SQL, Tableau, Excel 
  <br><br>
  <a href="https://www.linkedin.com/in/alexborschke/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/alexborschke?tab=repositories/">GitHub Repo</a>
  <br>
  <a href="https://public.tableau.com/app/profile/alexandra.borschke/">Tableau Public</a>
  <br><br>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
